### ISSUE TITLE
Make `sncast declare` work with scarb 2.7.0

### ISSUE THREAD

**Issue by ksew1** [foundry-rs/starknet-foundry#2352]
### Which component is your feature related to?

Cast

### Feature Request

When running `sncast declare` on Scarb 2.7.0, we get the following error:

```
error: An error occurred in the called contract = ContractErrorData { revert_error: "Sierra compilation error: Unable to compile Sierra to Casm. No matching ContractClass or CasmContractClass found for version 1.6.0" }
```

Because of this, the CI currently runs on the previous versions. After making `sncast declare` work with Scarb 2.7.0, please also change the CI to run on `2.7.0`. Additionally, unignore this test: `test_script_init_happy_case()`.

---

**Comment by integraledelebesgue** [comment]
Solving this issue is blocked until `devnet`'s next release and `starknet-rs` fix of [this issue](https://github.com/xJonathanLEI/starknet-rs/issues/649#issue-2469861847)

**Comment by integraledelebesgue** [comment]
We just need to bump `starknet-rs` to [`660a732`](https://github.com/xJonathanLEI/starknet-rs/commit/660a7323169bbcdaea71b4f0e939631e3aaabd45)

**Comment by integraledelebesgue** [comment]
It turns out that the issue still remains despite the `starknet-rs` fix - [`starknet-devnet-rs`](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/64e788afc961c65d8517801f481980f5bed8b9cd/Cargo.toml#L78) uses outdated `starknet-rs` dependencies without that fix.
Marking as `blocked` until `devnet` bumps SDK.

**Comment by qiaopengjun5162** [comment]
```bash
➜ sncast --profile dev-profile declare --contract-name ERC20 --fee-token strk
   Compiling snforge_scarb_plugin v0.31.0 (git+https://github.com/foundry-rs/starknet-foundry?tag=v0.31.0#72ea785ca354e9e506de3e5d687da9fb2c1b3c67)
    Finished `release` profile [optimized] target(s) in 0.16s
   Compiling starknet_erc20 v0.1.0 (/Users/qiaopengjun/Code/starknet-code/hello_starknet/starknet_erc20/Scarb.toml)
    Finished release target(s) in 4 seconds
[WARNING] Profile dev-profile does not exist in scarb, using 'release' profile.
command: declare
error: An error occurred in the called contract = ContractErrorData { revert_error: "Sierra compilation error: Unable to compile Sierra to Casm. No matching ContractClass or CasmContractClass found for version 1.6.0" }

```
Does anyone have a solution to this problem? What is the reason?
